name: Docker build

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - docker-compose.yaml
      - pyproject.toml
      - poetry.lock
      - src/**
  pull_request:
    paths:
      - Dockerfile
      - docker-compose.yaml
      - pyproject.toml
      - poetry.lock
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
          tool-cache: true

      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build --pull
